[project]
name = "dml-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "donky", email = "theojohnhenry@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.6.4",
    "kagglehub>=1.0.2",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "torch>=2.14.1",
    "wfdb>=4.3.1",
]

[project.scripts]
dml-project = "dml_project:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
